name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
    - name: sshdeploy
      uses: easingthemes/ssh-deploy@v2.0.7
      with:
        # Private Key
        SSH_PRIVATE_KEY: ${{secrets.ALIYUN}}
        # Remote host
        REMOTE_HOST: "118.190.105.213"
        # Remote user
        REMOTE_USER: "root"
        # Source directory
        SOURCE: "dist/"
        # Target directory
        TARGET: "/usr/local/nginx/admin/"
